# site settings
title: Transit Project
subtitle:
email: jacquemain.ainsley@gmail.com
description: Exploring exoplanet biosignatures with the quantitative analysis of transit data.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: https://jacquemainainsley.github.io # the base hostname & protocol for your site
author: Ainsley Jacquemain
street_address: McPherson Laboratory, 140 W 18th Ave
city: Columbus
state: OH
zip_code: 43210
country: United States of America
phone: (614) 292-1773

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/jacquemainainsley

# build settings
markdown: kramdown

sass:
  style: compressed
  
remote_theme: "andrewbanchich/forty-jekyll-theme"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  
exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
